### ISSUE TITLE
Default config file

### ISSUE THREAD

**Issue by MalteKiefer** [madflojo/efs2#22]
## Describe the idea

It would be an advantage to have a configuration file where you could write the default in, so you don't have to always give the parameters.

### Describe possible implementations

In the HOME directory, look in the .config folder for an `efs2` with a file named config.yml.
The structure could be as follows:

```yml
verbose: false
ssh_key: ~/.ssh/id_dsa
ssh_port: 2000
ssh_user: root
```

Maybe it is possible to adjust `config/config.go` so that it first searches for the config file, and then reads the parameters of the input from the terminal.
